### ISSUE TITLE
restore libco history

### ISSUE THREAD

**Issue by Screwtapello** [higan-emu/libco#2]
The current version of the libco repository is just a snapshot of the libco code as it was in the higan repo as of even date. It seems a shame to lose all the development history unnecessarily, and it's not too difficult to `git subtree split` it out. I propose we do that, and update this repo before too many people start git submoduling this commit ID into their code.

However, some questions remain:

- how much history to include?
    - we could just take all the history from the higan repo, which is reliable but incomplete
    - we could include history reconstructed from old source archives, which might be misleading if more source archives are discovered later (we don't want to rewrite history to include them)
- how do we update `master`?
    - if we force-push the new commit history, it will be clean, but could disrupt possible downstreams
    - if we merge the commit history, it will be weird glitch in the history, but it at least it should be simple for downstream users to follow the history.

**Comment by Screwtapello** [comment]
(for the record, I've already prepared a branch that includes all the history from old source archives, and I think adding history with a merge commit would be the safest)

**Comment by merryhime** [comment]
Apologies for this. Merging sounds like the best option.
