### ISSUE TITLE
Teach libco about valgrind

### ISSUE THREAD

**Issue by Screwtapello** [higan-emu/libco#24]
Valgrind is a great way to diagnose memory-safety issues, but it doesn't like libco very much - when libco switches to a new stack, Valgrind assumes that the entire span of memory from the old stack pointer to the new stack pointer is stack memory, and gets very confused.

Apparently Valgrind has [a client request API](https://www.valgrind.org/docs/manual/manual-core-adv.html#manual-core-adv.clientreq) that lets you tell valgrind "this region of memory is a new, unconnected stack" which should make valgrind much more reliable.

[Here](https://github.com/UIUC-PPL/charm/commit/bdf92bcac16482aaa17aed141e116daa2bd097bc) and [here](https://github.com/UIUC-PPL/charm/commit/8ecbc84c0e6049c305e72fc83a9e6db91e12f94a) are examples of the API in use.

To integrate this properly with libco, we would need to:

- copy the headers into the libco repository (they're BSD licensed, specifically to make this possible)
- add the relevant calls to creating and destroying stacks

I don't think we need to care about including the header only on supported platforms (the header is pretty good about platform detection as-is) or about including it only in debug builds (apparently the overhead is ~7 instructions, and creating/destroying coroutines shouldn't be on any hot path).

The Valgrind docs for the stack annotations say "Warning: Unfortunately, this client request is unreliable and best avoided" but they don't suggest any real alternative.

**Comment by namandixit** [comment]
[This webpage](https://graphitemaster.github.io/fibers/#debuggers) contains some more details about making it work with various debuggers and sanitizers, in addition to Valgrind.

**Comment by zuiderkwast** [comment]
Fixed by #39.

**Comment by Screwtapello** [comment]
To be clear, #39 tells Valgrind about stacks when they are created.

- it does not tell Valgrind about stacks when they are destroyed, but it doesn't seem to matter just yet
    - If it does matter, we can figure something out
- it does not add support for Address Sanitizer or Thread Sanitizer, because those tools don't report problems with our test apps

I'm calling this issue done, we can open new issues about specific issues if and when they occur.
