### ISSUE TITLE
Support building with MSVC

### ISSUE THREAD

**Issue by beaumanvienna** [higan-emu/libco#34]
Hi there, I'm trying to compile the example `test_timing.cpp` under Windows. MSys2+MinGW-gcc worked.
With VS2019, however, I get

`C2341 segment must be defined using #pragma data_seg, code_seg or section prior to use`

in amd64.c [here](https://github.com/higan-emu/libco/blob/fba00e5d3404e1bcfe1007ee2e3bfc3b3bb888af/amd64.c#L16)

If I change it to 
```
  #ifdef _MSC_VER
    #pragma data_seg(".text")
  #endif
```
I get `libco.obj : warning LNK4078: multiple '.text' sections found with different attributes (60500020)`. 
Please advise.
Thank you!

**Comment by beaumanvienna** [comment]
Also, I get this access violation:
![2021-09-12 20_08_55-testing (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/7109443/133018250-569afe70-3335-4bc1-8dcd-6e0f851d3bf3.png)

**Comment by beaumanvienna** [comment]
If you would like to reproduce this issue, this is the premake file I used to generate the project. The extension should be changed to `.lua`. Thank you again! 
[premake5.txt](https://github.com/higan-emu/libco/files/7151165/premake5.txt)

**Comment by Screwtapello** [comment]
The `co_swap_function` global variable actually contains program code, not data, so the linker needs to be told to store it in the code segment, not the data segment. In Unixy platforms (and apparently MinGW) this segment is called "text", which is why we have `section(text)` and similar incantations, but I don't know how to achieve that with MSVC. Possibly `#pragma code_seg(".text")` is part of it, but that's just a guess based on the error messages you pasted.

If you figure out how to get it working, and it's not too invasive, I would review a PR to add MSVC support.

**Comment by merryhime** [comment]
Current support for MSVC requires you to have `LIBCO_MPROTECT` defined; this would use `VirtualProtect` on Windows to ensure the memory has the appropriate permissions at runtime.

--- 

Reading documentation, it appears that this should work:
```
#pragma section(".text") 

__declspec(allocate(".text"))
static const unsigned char co_swap_function[4096] = {
```
Would you be able to test?

**Comment by beaumanvienna** [comment]
It works. All's I had to do was define `LIBCO_MPROTECT` and uncomment `alignas(4096)`

**Comment by beaumanvienna** [comment]
### context-switching timing test

MinGW-gcc/Release
```
0.789 seconds per  50 million subroutine calls (500000000 iterations)
10.147 seconds per 100 million co_switch  calls (500000000 iterations)
co_switch skew = 12.860583x
```
MSVC/Release
```
0.968 seconds per  50 million subroutine calls (500000000 iterations)
7.018 seconds per 100 million co_switch  calls (500000000 iterations)
co_switch skew = 7.250000x
```

**Comment by beaumanvienna** [comment]
Same machine, under Ubuntu
```
context-switching timing test

0.824 seconds per  50 million subroutine calls (500000000 iterations)
3.252 seconds per 100 million co_switch  calls (500000000 iterations)
co_switch skew = 3.945070x
```

**Comment by beaumanvienna** [comment]
@merryhime  @Screwtapello Could you please review my PR? I hope adding premake is ok for you? 

There is at least one mistake in my PR [here](https://github.com/beaumanvienna/libco/blob/15b839249069da0370597fa4150e7eabdfc38e4f/doc/examples/premake5.lua#L48). This filters every Visual Studio project. Since VS is also a thing on macOS, this line should read
`filter { "system:windows", "action:vs*" }`

**Comment by Screwtapello** [comment]
Our new GitHub Actions CI builds and runs our examples on MSVC, so I believe MSVC is now properly supported.
