### ISSUE TITLE
How to pass parameter to entry function?

### ISSUE THREAD

**Issue by lygstate** [higan-emu/libco#5]

**Comment by Screwtapello** [comment]
The (freshly converted to Markdown) docs [say](https://github.com/higan-emu/libco/blob/master/doc/usage.md#co_create):

> This function does not take any arguments, due to portability issues with passing function arguments. However, arguments can be simulated by the use of global variables, which can be set before the first call to each cothread.

You should be able to do something like:

- make a global variable named `REAL_FUNC` containing a function pointer that takes a `void *` argument
- make a global variable named `REAL_ARGS` containing a `void *`
- make a wrapper function that takes no arguments, but calls `REAL_FUNC(REAL_ARGS)`
- when you want to spawn a function in a thread, assign the function to `REAL_FUNC`, the argument to `REAL_ARGS`, and spawn the wrapper function instead

**Comment by lygstate** [comment]
Well, this would cause problems when we spawning a lots of threads.

**Comment by lygstate** [comment]
For example,  https://github.com/geky/coru support for pass parameter to entry function

**Comment by lygstate** [comment]
I found a way to pass parameter in a general way
According to this
https://github.com/geky/coru/issues/3

**Comment by lygstate** [comment]
We can use a extra data structure to storage arg info
